### ISSUE TITLE
[Bug Report] <Subtlety Rogue GCD Error>

### ISSUE THREAD

**Issue by Beyonderr** [Merathilis/ElvUI_MerathilisUI#50] opened 2022-11-01 17:04 UTC
### What is the issue you are having?

Error spam message in chat when you push any button (only for subtlety rogue):
oUF_GCD: Missing Spell Data

### What is the expected behavior?

No errors

### What actually happened?

Spam oUF_GCD: Missing Spell Data

### Errors

```shell
oUF_GCD: Missing Spell Data only in subtlety rogues
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.

**Comment by Merathilis** [comment] 2022-11-01 18:20
Can't confirm that issue. Also you havent tell me if the issue is on Retail or Classic. Since i dont play Classic i tested it on Retail.

**Comment by Beyonderr** [comment] 2022-11-01 18:41
MerathilisUI Retail.  
Error in chat with sub rogues (I tested in 4 rogues) [https://imgur.com/YUT5yV8](url)

**Comment by Merathilis** [comment] 2022-11-01 18:43
Please share me your Talents here please, cause i was unable to test it.. could be some special talent which replace the actual spell that is needed for the gcd

**Comment by Beyonderr** [comment] 2022-11-01 18:49
Talents:

BUQAOB/7AZ//CwQOf4fPMswHVDAAIBAAAAAAQIhkEJQSQSIQQSSiQkmkkESa0SiAQAAAA

**Comment by Merathilis** [comment] 2022-11-02 07:55
Fixed with the commit mentioned above ^ Thanks for the report

**Closed** 2022-11-02 07:54 UTC
